### ISSUE TITLE
Button Merge

### ISSUE THREAD

**Issue by tomtomklima** [ParalelniPolis/bitcoinJukebox#1]
Can we merge buttons after song choosing, particulary Objednat a Zaplatit?

**Comment by racinmat** [comment]
Propably yes, but I need to figure how to post selected songs to the server and redirect user to bitcoin wallet in one step.
And if redirect from the serveside to bitcoin wallet wont work, maybe automatic click on the Zaplatit button by javascript will do the job.

**Comment by racinmat** [comment]
Done, you may try it now.
